// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SparePartsWarehouse.DATA.Context;

#nullable disable

namespace SparePartsWarehouse.DATA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260125130346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SparePartsWarehouse.CORE.DTO.ItemMovement", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vw_ItemMovement", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.DTO.MachineSparePartsCostDetailDto", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryDepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("MachineSparePartsCost");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.DTO.MachineSparePartsCostDto", b =>
                {
                    b.Property<string>("FactoryDepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("MachineSparePartsCosts");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.DTO.StockBalanceDto", b =>
                {
                    b.Property<decimal>("BalanceQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalInQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOutQty")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vw_StockBalance", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StoreDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreDepartmentId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "سيور",
                            StoreDepartmentId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "رولمان بلي",
                            StoreDepartmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "تروس",
                            StoreDepartmentId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "مواتير",
                            StoreDepartmentId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "لمبات",
                            StoreDepartmentId = 2
                        });
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.DocumentEditsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentEditsLogs", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.FactoryDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FactoryDepartments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "الجلد"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "النسيج"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "قطع غيار"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "الاداره"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "مخزن"
                        });
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemName", "CategoryId")
                        .IsUnique();

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.ItemDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ItemCode")
                        .IsUnique();

                    b.ToTable("ItemDescriptions", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FactoryDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryDepartmentId");

                    b.HasIndex("MachineName", "FactoryDepartmentId")
                        .IsUnique();

                    b.ToTable("Machines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FactoryDepartmentId = 1,
                            MachineName = "الخط القديم"
                        },
                        new
                        {
                            Id = 2,
                            FactoryDepartmentId = 1,
                            MachineName = "الخط الجديد"
                        },
                        new
                        {
                            Id = 3,
                            FactoryDepartmentId = 1,
                            MachineName = "خلاط"
                        },
                        new
                        {
                            Id = 4,
                            FactoryDepartmentId = 1,
                            MachineName = "طباعه"
                        },
                        new
                        {
                            Id = 5,
                            FactoryDepartmentId = 1,
                            MachineName = "امبوز"
                        },
                        new
                        {
                            Id = 6,
                            FactoryDepartmentId = 1,
                            MachineName = "كاردا"
                        },
                        new
                        {
                            Id = 7,
                            FactoryDepartmentId = 1,
                            MachineName = "مقص"
                        },
                        new
                        {
                            Id = 8,
                            FactoryDepartmentId = 1,
                            MachineName = "اللفاف"
                        },
                        new
                        {
                            Id = 9,
                            FactoryDepartmentId = 1,
                            MachineName = "الفرز"
                        },
                        new
                        {
                            Id = 10,
                            FactoryDepartmentId = 1,
                            MachineName = "مرافق"
                        },
                        new
                        {
                            Id = 11,
                            FactoryDepartmentId = 1,
                            MachineName = "كلارك"
                        },
                        new
                        {
                            Id = 12,
                            FactoryDepartmentId = 1,
                            MachineName = "اسانسير"
                        },
                        new
                        {
                            Id = 13,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 1 اورزيو"
                        },
                        new
                        {
                            Id = 14,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 2 اورزيو"
                        },
                        new
                        {
                            Id = 15,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 3 اورزيو"
                        },
                        new
                        {
                            Id = 16,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 4 اورزيو"
                        },
                        new
                        {
                            Id = 17,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 5 باى لونج"
                        },
                        new
                        {
                            Id = 18,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 6 سانج يونج"
                        },
                        new
                        {
                            Id = 19,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 7 الجديده"
                        },
                        new
                        {
                            Id = 20,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 8 "
                        },
                        new
                        {
                            Id = 21,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 9   جاكار "
                        },
                        new
                        {
                            Id = 22,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 10 فرو"
                        },
                        new
                        {
                            Id = 23,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 11 فرو"
                        },
                        new
                        {
                            Id = 24,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 12 فرو"
                        },
                        new
                        {
                            Id = 25,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 13 فرو"
                        },
                        new
                        {
                            Id = 26,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 14 فرو"
                        },
                        new
                        {
                            Id = 27,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 15 بو ليستر لامع"
                        },
                        new
                        {
                            Id = 28,
                            FactoryDepartmentId = 2,
                            MachineName = "ماكينه 16 فرو أكرليليك"
                        },
                        new
                        {
                            Id = 29,
                            FactoryDepartmentId = 3,
                            MachineName = "عدد و ادوات"
                        },
                        new
                        {
                            Id = 30,
                            FactoryDepartmentId = 4,
                            MachineName = "مرافق"
                        },
                        new
                        {
                            Id = 31,
                            FactoryDepartmentId = 5,
                            MachineName = "اخرى"
                        },
                        new
                        {
                            Id = 32,
                            FactoryDepartmentId = 5,
                            MachineName = "مرافق"
                        });
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.PurchaseIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumberInvoice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PurchasedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseIns", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.PurchaseInDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageUnitCost")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ItemDescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseInId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemDescriptionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseInId");

                    b.ToTable("PurchaseInDetails", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemDescriptionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemDescriptionId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StockOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FactoryDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("IssuerName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("Ahmed");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StoreDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactoryDepartmentId");

                    b.HasIndex("MachineId");

                    b.HasIndex("StoreDepartmentId");

                    b.ToTable("StockOuts", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StockOutDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageUnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ItemDescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("StockOutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemDescriptionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId1");

                    b.HasIndex("StockOutId", "ItemId", "ItemDescriptionId")
                        .IsUnique();

                    b.ToTable("StockOutDetails", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StoreDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StoreDepartment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "ميكانيكا"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "كهرباء"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "عدد وقطع تشغيل"
                        });
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierName")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Category", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.StoreDepartment", "StoreDepartment")
                        .WithMany("Categories")
                        .HasForeignKey("StoreDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreDepartment");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Item", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.ItemDescription", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.Item", "Item")
                        .WithMany("Descriptions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Machine", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.FactoryDepartment", "FactoryDepartment")
                        .WithMany("Machines")
                        .HasForeignKey("FactoryDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FactoryDepartment");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.PurchaseIn", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.PurchaseInDetail", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.ItemDescription", "ItemDescription")
                        .WithMany()
                        .HasForeignKey("ItemDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SparePartsWarehouse.CORE.Entities.Item", "Item")
                        .WithMany("PurchaseInDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SparePartsWarehouse.CORE.Entities.PurchaseIn", "PurchaseIn")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemDescription");

                    b.Navigation("PurchaseIn");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StockAdjustment", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.ItemDescription", "ItemDescription")
                        .WithMany()
                        .HasForeignKey("ItemDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDescription");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StockOut", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.FactoryDepartment", "FactoryDepartment")
                        .WithMany()
                        .HasForeignKey("FactoryDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SparePartsWarehouse.CORE.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SparePartsWarehouse.CORE.Entities.StoreDepartment", "StoreDepartment")
                        .WithMany()
                        .HasForeignKey("StoreDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FactoryDepartment");

                    b.Navigation("Machine");

                    b.Navigation("StoreDepartment");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StockOutDetail", b =>
                {
                    b.HasOne("SparePartsWarehouse.CORE.Entities.ItemDescription", "ItemDescription")
                        .WithMany()
                        .HasForeignKey("ItemDescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SparePartsWarehouse.CORE.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SparePartsWarehouse.CORE.Entities.Item", null)
                        .WithMany("StockOutDetails")
                        .HasForeignKey("ItemId1");

                    b.HasOne("SparePartsWarehouse.CORE.Entities.StockOut", "StockOut")
                        .WithMany("Details")
                        .HasForeignKey("StockOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemDescription");

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.FactoryDepartment", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.Item", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("PurchaseInDetails");

                    b.Navigation("StockOutDetails");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.PurchaseIn", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StockOut", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("SparePartsWarehouse.CORE.Entities.StoreDepartment", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
